
type Summary = {
  removed: number;
  removedByCollection: Record<string, number>;
  clearedMetadata: boolean;
};

function idSet(rows: any[]) {
  return new Set((Array.isArray(rows) ? rows : []).map((row) => String(row?.id ?? '')).filter(Boolean));
}

function matchesSeedTimestamp(row: any, seedStamp: string) {
  return !!seedStamp && String(row?.createdAt || '') === seedStamp;
}

function filterCollection(db: any, key: string, predicate: (row: any) => boolean, summary: Summary) {
  const rows = Array.isArray(db?.[key]) ? db[key] : [];
  const kept = rows.filter((row: any) => !predicate(row));
  const removed = rows.length - kept.length;
  if (removed > 0) {
    db[key] = kept;
    summary.removed += removed;
    summary.removedByCollection[key] = removed;
  }
}

export function sanitizeAccidentalTestData(source: any): { db: any; summary: Summary } {
  const db = source && typeof source === 'object' ? JSON.parse(JSON.stringify(source)) : {};
  const summary: Summary = { removed: 0, removedByCollection: {}, clearedMetadata: false };
  const meta = db?._meta && typeof db._meta === 'object' ? db._meta : {};
  const seedProfile = String(meta.seedProfile || '').trim();
  const seedStamp = String(meta.seededAt || '').trim();

  // A production database is eligible only when the deterministic test profile
  // marker is present. This deliberately avoids guessing at real shop records.
  if (seedProfile !== 'test-week') return { db, summary };

  const fakeCustomerIds = idSet((db.customers || []).filter((row: any) =>
    /@example\.com$/i.test(String(row?.email || '')) &&
    /^803-100-\d{4}$/.test(String(row?.phone || '')),
  ));

  filterCollection(db, 'customers', (row) => fakeCustomerIds.has(String(row?.id ?? '')), summary);
  const fakeWorkOrderIds = idSet((db.workOrders || []).filter((row: any) =>
    String(row?.intakeSource || '').trim() === 'Test Environment' ||
    String(row?.serial || '').trim() === 'TEST-SERIAL',
  ));
  filterCollection(db, 'workOrders', (row) => fakeWorkOrderIds.has(String(row?.id ?? '')), summary);

  const fakeSaleIds = idSet((db.sales || []).filter((row: any) =>
    String(row?.intakeSource || '').trim() === 'Test Environment',
  ));
  filterCollection(db, 'sales', (row) => fakeSaleIds.has(String(row?.id ?? '')), summary);

  const linkedToGeneratedTicket = (row: any) =>
    fakeWorkOrderIds.has(String(row?.workOrderId ?? '')) ||
    fakeSaleIds.has(String(row?.saleId ?? ''));

  for (const key of ['quotes', 'calendarEvents', 'calendarNotes', 'purchaseOrders', 'notifications']) {
    filterCollection(db, key, linkedToGeneratedTicket, summary);
  }
  filterCollection(db, 'clientResponses', (row) =>
    linkedToGeneratedTicket(row) || /^reply-test-/i.test(String(row?.id || '')),
  summary);

  // Catalog and lookup rows generated by the test profile share its exact
  // seed timestamp; genuine rows are retained even if IDs overlap.
  for (const key of [
    'products', 'repairCategories', 'repairTypes', 'deviceCategories',
    'productCategories', 'technicians', 'settings',
  ]) {
    filterCollection(db, key, (row) => matchesSeedTimestamp(row, seedStamp), summary);
  }

  if (Array.isArray(db.addressHistory)) db.addressHistory = [];
  delete db._meta;
  summary.clearedMetadata = true;
  return { db, summary };
}
