import React, { useEffect, useState } from 'react';
import { listTechnicians, technicianDisplayName } from '@/lib/admin';
type Period='opening'|'follow_up'|'closing';
const templates:Record<Period,{title:string;time:string;items:string[]}>={
opening:{title:'Opening',time:'10:00–10:50 AM',items:['Open shop; lights and music on','Power on POS, payment equipment, and displays','Clean counters, intake/register area, glass, stations, and floors as needed','Review Needs Attention, replies, active tickets, and pickups','Review EOD Cart, deliveries, inventory, and today’s assigned tasks']},
follow_up:{title:'Client follow-up',time:'10:50–11:00 AM',items:['Review status and pickup follow-ups','Send QR/email update first','Call clients when needed','Record promises, replies, and next action']},
closing:{title:'Closing',time:'After 7:00 PM',items:['Complete remaining client updates and pickup reminders','Reconcile Command Center, Needs Attention, delivery tracking, EOD Cart, and balances','Verify repair stage, technician note, and next action','Clean counters, intake/register area, stations, and floors as needed','Put the day’s cash in the safe','Secure client devices, parts, stations, lights, music, doors, and alarm']},};
const dateKey=()=>new Date().toLocaleDateString('en-CA');
export default function DailyOperationsWindow({onClose}:{onClose:()=>void}){
const api:any=(window as any).api;const[rows,setRows]=useState<any[]>([]);const[settings,setSettings]=useState<any>(null);const[techs,setTechs]=useState<any[]>([]);const[period,setPeriod]=useState<Period>('opening');const[techId,setTechId]=useState('');const[checked,setChecked]=useState<Record<string,boolean>>({});const[history,setHistory]=useState(false);const today=dateKey();
const load=async()=>{const settingsRows=await api?.dbGet?.('settings')||[];const record=settingsRows[0]||null;const cutoff=Date.now()-30 * 86400000;const all=Array.isArray(record?.dailyOperationsChecklists)?record.dailyOperationsChecklists:[];const keep=all.filter((row:any)=>new Date(row.submittedAt||0).getTime()>=cutoff);setSettings(record);setRows(keep);if(record&&keep.length!==all.length)await api?.dbUpdate?.('settings',record.id,{...record,dailyOperationsChecklists:keep,updatedAt:new Date().toISOString()});};
useEffect(()=>{void load();void listTechnicians().then(setTechs).catch(()=>{});},[]);
const current=rows.find(row=>row.dateKey===today&&row.period===period);const template=templates[period];const completed=template.items.filter((_,i)=>checked[String(i)]).length;
const submit=async()=>{if(!techId||current)return;const now=new Date().toISOString();const technician=techs.find(row=>String(row.id)===techId);const payload={id:crypto.randomUUID(),dateKey:today,period,technicianId:techId,technicianName:technicianDisplayName(technician),submittedAt:now,items:template.items.map((label,i)=>({label,checked:!!checked[String(i)]})),completedCount:completed,totalCount:template.items.length,createdAt:now,updatedAt:now};const next=[...rows.filter(row=>!(row.dateKey===today&&row.period===period)),payload];const updated={...(settings||{}),dailyOperationsChecklists:next,updatedAt:now};const saved=settings?.id!=null?await api?.dbUpdate?.('settings',settings.id,updated):await api?.dbAdd?.('settings',{...updated,createdAt:now});setSettings(saved||updated);setRows(next);};
const entries=rows.filter(row=>row.dateKey===today||new Date(row.submittedAt).getTime()>=Date.now()-30 * 86400000).sort((a,b)=>String(b.submittedAt).localeCompare(String(a.submittedAt)));
return <div className="command-center-panel-layer" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="command-center-panel" style={{maxWidth:720}}><header><h2>{history?'Checklist History':'Opening / Closing Checklist'}</h2><div><button onClick={()=>setHistory(v=>!v)}>{history?'Today':'History'}</button><button aria-label="Close" onClick={onClose}>×</button></div></header>{history?<div className="command-center-panel-table"><table><thead><tr><th>Date</th><th>Checklist</th><th>Technician</th><th>Complete</th><th>Submitted</th></tr></thead><tbody>{entries.map(row=><tr key={row.id}><td>{row.dateKey}</td><td>{templates[row.period as Period]?.title||row.period}</td><td>{row.technicianName}</td><td>{row.completedCount}/{row.totalCount}</td><td>{new Date(row.submittedAt).toLocaleString()}</td></tr>)}</tbody></table>{!entries.length?<p className="command-center-empty">No checklist submissions in the last 30 days.</p>:null}</div>:<div className="p-4"><div className="flex gap-2 flex-wrap mb-4">{(Object.keys(templates) as Period[]).map(key=><button key={key} className={period===key?'active':''} onClick={()=>{setPeriod(key);setChecked({})}}>{templates[key].title}{rows.some(row=>row.dateKey===today&&row.period===key)?' ✓':''}</button>)}</div><p className="text-sm text-zinc-400">{template.time} · {current?'Submitted — Read-only':'Select technician, complete what applies, then submit.'}</p>{!current?<label className="block my-3 text-sm">Technician <select className="ml-2 bg-zinc-800 border border-zinc-700 rounded px-2 py-1" value={techId} onChange={e=>setTechId(e.target.value)}><option value="">Select technician</option>{techs.map(t=><option key={t.id} value={String(t.id)}>{technicianDisplayName(t)}</option>)}</select></label>:<p className="text-sm text-[#39ff14]">Submitted by {current.technicianName} · {new Date(current.submittedAt).toLocaleTimeString()}</p>}<div>{template.items.map((label,i)=>{const done=current?current.items?.[i]?.checked:checked[String(i)];return <label key={label} className="flex gap-3 py-3 border-t border-zinc-800 text-sm"><input type="checkbox" disabled={!!current} checked={!!done} onChange={e=>setChecked(v=>({...v,[String(i)]:e.target.checked}))}/><span>{label}</span></label>})}</div>{!current?<footer className="mt-4 flex justify-between"><span className="text-sm text-zinc-400">{completed}/{template.items.length} checked</span><button className="confirm" disabled={!techId} onClick={()=>void submit()}>Submit checklist</button></footer>:null}</div>}</section></div>;}